# .github/workflows/deploy-to-prod.yml
name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*' # This pattern matches production tags

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Await Manual Approval
      uses: chrnorm/deployment-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ENVIRONMENT: production

    - name: Simulate Deployment to Prod
      run: echo "Simulate deployment to environment PROD"
